name: DotNet CI/CD

on: [push]

jobs:
    # name: build & test on win/linux
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-dotnet@v1
          with: 
            dotnet-version: 5.0.x
        - name: Build Project
          run: dotnet build
        - name: Run Tests
          run: dotnet test
          
    Build-and-Push-Docker-Image:
        runs-on: ubuntu-latest
        needs: build
        name: Docker Build, Tag, Push

        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Download built artifact
          uses: actions/download-artifact@main
          with:
            name: dotnet artifacts
            path: public
        - name: Build container image
          uses: docker/build-push-action@v2
          with:
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}
            registry: docker.pkg.github.com
            repository: bjork-dev/cicd/dotnet-app
            tag_with_sha: true