name: DotNet CI / CD

on:
  push:
    paths:
      - "**Dockerfile**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: 5.0.x
    - name: Build Project
      run: dotnet build ./Source/SpacePark/
    - name: Run Space Tests
      run: dotnet test ./Source/SpaceTests/
          
  Build-and-Push-Docker-Image:
      runs-on: ubuntu-latest
      needs: test
      name: Docker Build, Tag, Push

      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download built artifact
        uses: actions/download-artifact@main
        with:
          name: dotnet artifacts
          path: public
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: docker.pkg.github.com
          repository: bjork-dev/cicd/dotnet-app
          tag_with_sha: true