name: DotNet CI/CD

on: [push]

jobs:
    # name: build & test on win/linux
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-dotnet@v1
          with: 
            dotnet-version: 3.1.x
        - name: Build Project
          run: dotnet build
        - name: Run Tests
          run: dotnet test
          
    Build-and-Push-Docker-Image:
        runs-on: ubuntu-latest
        needs: build
        name: Docker Build, Tag, Push
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Log in to the Container registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        - name: Build and push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}