name: DotNet CI/CD

on: [push]

jobs:
    # name: build & test on win/linux
    build:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-dotnet@v1
          with: 
            dotnet-version: 3.1.x
        - name: Build Project
          run: dotnet build
        - name: Run Tests
          run: dotnet test
          
    Build-and-Push-Docker-Image:
        runs-on: ubuntu-latest
        needs: build
        name: Docker Build, Tag, Push

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Log in to the Container registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io # Github Container Registry
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: ${{ github.actor }}/${{ github.repository }}:latest
            secrets: |
                GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
