name: DotNet CI/CD

on: [push]

jobs:
    # name: build & test on win/linux
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-dotnet@v1
          with: 
            dotnet-version: 3.1.x
        - name: Build Project
          run: dotnet build
        - name: Run Tests
          run: dotnet test
          
    Build-and-Push-Docker-Image:
        runs-on: ubuntu-latest
        needs: build
        name: Docker Build, Tag, Push

        steps:
        - name: Checkout
          uses: actions/checkout@v2
          name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build container image
          uses: docker/build-push-action@v2
          with:
            push: true
            # repository: bjork-dev/cicd/dotnet-app
            tags: user/app:latest