name: DotNet CI/CD

on: [push]

jobs:
    # name: build & test on win/linux
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-dotnet@v1
          with: 
            dotnet-version: 5.0.x
        - name: Build Project
          run: dotnet build
        - uses: actions/upload-artifact@master
          with:
            name: dotnet artifacts
            path: .
        - name: Run Tests
          run: dotnet test
          
    Build-and-Push-Docker-Image:
        runs-on: ubuntu-latest
        needs: build
        name: Docker Build, Tag, Push

        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Download built artifact
          uses: actions/download-artifact@main
          with:
            name: dotnet artifacts
            path: publish
        - name: Build container image
          uses: docker/build-push-action@v1
          with:
            push: true
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}
            registry: docker.pkg.github.com
            repository: bjork-dev/github-actions-for-packages/tic-tac-toe
            tags: user/app:latest